travis:
  secure:
    BINSTAR_TOKEN: Mkz/2f2sx++2myVXKcdp9Go3wVPc4bcNG/sclWLncgpIkAWzPo8QQgjUIIRwLPzqppdsqQf2KLhzMsIGZMK6HRpC7KSFt7Hwjty9VSHmUnHMf7tmGgNb7eagBWZOiOZ7vaEBCSJVZ18dCDRrTmbIm9ElrNFy/QCmby1cV6BYfj4PpWuM9PQu+ltqzYc6TJyPZ2E7wIz2zibwRDUmpEP5dN62jnBMge00bRIfJ/GvnD2o6rPu47LMvBj2/56fLbLHUaSy5xJakNfFVUL3zhfO55+pL7v4oKMWBasa+PofJ4xKIPOJVxOM6DyTpOYz+imBXCYZQvfHC3WATDQDrCYWRb5ZR2pDUogq9Chm4Idnb3i1nUgCk39eInEmMc9hZCG1TNeeD6CrT4yjNfJc4KAXrL/GpMq/Qth19U+SyaLtJ3OO75nH6fY6RE/WgS0p06kDrtmsf8WCocWBzcTy7GuyXBGh3zkpS/gmStd4gEsrYCYWzMTfuzTUT/5pkG5pwYxN77TbLEdUirkTXNtfLugC1SPR3MBPlwkyyPiQqEnmUwDVd8lvjt9b4/OhYcIkb4I14RokPLcE6wmgzrEgEGDxLoYNfm9VyyfH+mpgccf6UyQC1TC23EgqHOmuwr5IxiTF1g+FbiJbxrcICIVyBNtnrZeBeDzFFY62cUIYj1pkdig=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
